title: Artifex Docs
description: A simple documentation website
theme: just-the-docs

url: https://jan-dro.github.io/darkpad-docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
search_enabled: true

# Navigation sections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
nav_enabled: true
